# Generated by Django 3.0.2 on 2020-01-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.IntegerField()),
                ('group', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('group', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='student', max_length=20)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=16)),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_to_guid', to='diht_feedback_collector.Guid')),
            ],
        ),
    ]
