# Generated by Django 3.0.2 on 2020-01-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diht_feedback_collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='people_to_guid', to='diht_feedback_collector.People')),
            ],
        ),
    ]
