# Generated by Django 3.0.2 on 2020-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.IntegerField()),
                ('group', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
